// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR9owjV3KEnDXP9mCdiGypTOzG6F0yrbM',
    appId: '1:1076257161622:web:faf61478ad7ded7b135db7',
    messagingSenderId: '1076257161622',
    projectId: 'matching-app-ecbbe',
    authDomain: 'matching-app-ecbbe.firebaseapp.com',
    storageBucket: 'matching-app-ecbbe.appspot.com',
    measurementId: 'G-N7HKYRDKZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWTNgn2y8npDoGs0Y8P6Wkibxw5GQnA6Y',
    appId: '1:1076257161622:android:44ace1d12ba4f4f5135db7',
    messagingSenderId: '1076257161622',
    projectId: 'matching-app-ecbbe',
    storageBucket: 'matching-app-ecbbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdr3S-z2tjJJDhnSNI1kfarOzXjDIlz5U',
    appId: '1:1076257161622:ios:a99d4385c1fe8d06135db7',
    messagingSenderId: '1076257161622',
    projectId: 'matching-app-ecbbe',
    storageBucket: 'matching-app-ecbbe.appspot.com',
    iosClientId: '1076257161622-lan9tljvgkr1bhpn6nebr6usk2iq95jq.apps.googleusercontent.com',
    iosBundleId: 'com.example.matchingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdr3S-z2tjJJDhnSNI1kfarOzXjDIlz5U',
    appId: '1:1076257161622:ios:a99d4385c1fe8d06135db7',
    messagingSenderId: '1076257161622',
    projectId: 'matching-app-ecbbe',
    storageBucket: 'matching-app-ecbbe.appspot.com',
    iosClientId: '1076257161622-lan9tljvgkr1bhpn6nebr6usk2iq95jq.apps.googleusercontent.com',
    iosBundleId: 'com.example.matchingApp',
  );
}
